import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { STRATEGY_OPTIONS } from '@/types';

function generateRandomTrade(accountId: string, userId: string, daysAgo: number) {
  const isWin = Math.random() > 0.45; // 55% win rate
  const strategy = STRATEGY_OPTIONS[Math.floor(Math.random() * STRATEGY_OPTIONS.length)];
  const direction = Math.random() > 0.5 ? 'LONG' : 'SHORT';
  
  const entryPrice = 50000 + (Math.random() * 10000);
  const size = 0.5 + (Math.random() * 2);
  const leverage = Math.floor(Math.random() * 10) + 1;
  
  // 1 to 4 hours duration
  const durationMs = (Math.floor(Math.random() * 3) + 1) * 60 * 60 * 1000;
  
  const entryTime = new Date(Date.now() - (daysAgo * 24 * 60 * 60 * 1000));
  const closeTime = new Date(entryTime.getTime() + durationMs);

  let exitPrice;
  if (isWin) {
    const move = entryPrice * (0.01 + Math.random() * 0.02); // 1-3% move
    exitPrice = direction === 'LONG' ? entryPrice + move : entryPrice - move;
  } else {
    const move = entryPrice * (0.005 + Math.random() * 0.015); // 0.5-2% move
    exitPrice = direction === 'LONG' ? entryPrice - move : entryPrice + move;
  }

  return {
    account_id: accountId,
    user_id: userId,
    ticker: ['BTC/USD', 'ETH/USD', 'SOL/USD', 'EUR/USD', 'NQ1!'][Math.floor(Math.random() * 5)],
    direction,
    entry_price: entryPrice,
    exit_price: exitPrice,
    stop_loss: direction === 'LONG' ? entryPrice * 0.98 : entryPrice * 1.02,
    take_profit: direction === 'LONG' ? entryPrice * 1.04 : entryPrice * 0.96,
    position_size: Number(size.toFixed(2)),
    leverage,
    entry_time: entryTime.toISOString(),
    close_time: closeTime.toISOString(),
    fees: Number((Math.random() * 5).toFixed(2)),
    strategy,
    reason: "Demo trade generated by system.",
  };
}

export async function GET() {
  const supabase = await createClient();
  
  // 1. Get current user
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  // 2. Create Demo Account
  const { data: account, error: accError } = await supabase
    .from('accounts')
    .insert({
      user_id: user.id,
      name: 'Demo Account',
      starting_balance: 10000,
      currency: 'USD',
      account_type: 'PERSONAL'
    })
    .select()
    .single();

  if (accError || !account) {
    return NextResponse.json({ error: "Failed to create demo account", details: accError }, { status: 500 });
  }

  // 3. Generate 50 trades over the last 90 days
  const trades = [];
  for (let i = 0; i < 50; i++) {
    // Random day between 1 and 90 days ago
    const daysAgo = Math.floor(Math.random() * 90) + 1;
    trades.push(generateRandomTrade(account.id, user.id, daysAgo));
  }

  // Sort them chronologically just in case
  trades.sort((a, b) => new Date(a.entry_time).getTime() - new Date(b.entry_time).getTime());

  // 4. Insert trades
  const { error: tradesError } = await supabase
    .from('trades')
    .insert(trades);

  if (tradesError) {
    return NextResponse.json({ error: "Failed to insert demo trades", details: tradesError }, { status: 500 });
  }

  // 5. Update user profile to set active account to the new demo account
  await supabase
    .from('profiles')
    .update({ active_account_id: account.id })
    .eq('id', user.id);

  // Redirect to dashboard analytics
  return NextResponse.redirect(new URL('/dashboard/analytics', process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'));
}
